import type { Metadata } from "next";
import { InfoPage } from "../legal-page";

export const metadata: Metadata = { title: "Data and licenses", description: "AeroWisp data sources, attribution, and license notes." };
const toc = [{ id: "en-app", label: "AeroWisp" }, { id: "en-live", label: "Live airspace data" }, { id: "en-demo", label: "Recorded Demo" }, { id: "en-third", label: "Third-party notices" }];
const tocZh = [{ id: "zh-app", label: "AeroWisp" }, { id: "zh-live", label: "实时空域数据" }, { id: "zh-demo", label: "Recorded Demo" }, { id: "zh-third", label: "第三方声明" }];

export default function LicensesPage() { return <InfoPage eyebrow="AeroWisp data & licenses" eyebrowZh="AeroWisp 数据与许可" title="Know what you are seeing." titleZh="看清你看到的是什么。" intro="A clear distinction between AeroWisp’s original instrument, its bounded synthetic demo, and external live-data providers." introZh="清楚区分 AeroWisp 的原创仪表、有边界的合成演示，以及外部实时数据提供方。" meta="Last updated August 16, 2026" metaZh="最后更新：2026 年 8 月 16 日" toc={toc} tocZh={tocZh}><div data-lang="en">
    <div className="callout warning-callout"><p><strong>Attribution is not a promise of availability.</strong> Provider coverage, terms, endpoints, and commercial permissions can change. Check the provider’s current official terms before distribution or commercial use.</p></div>
    <section aria-labelledby="en-app"><h2 id="en-app">1. AeroWisp original work</h2><p>AeroWisp’s original code, interface, visual systems, bundled configuration, recorded scene composition, documentation, and brand are © 2026 guogxy, all rights reserved, except where a third-party notice applies. The radar visual language is an original cinematic interpretation and does not copy a film, game, or other entertainment IP.</p></section>
    <section aria-labelledby="en-live"><h2 id="en-live">2. Live airspace data</h2><p>Live aircraft data may be provided by <a href="https://adsb.lol/" target="_blank" rel="noopener noreferrer">adsb.lol</a> when that source is configured in the app. Information from adsb.lol is made available under the <a href="https://opendatacommons.org/licenses/odbl/1-0/" target="_blank" rel="noopener noreferrer">Open Database License (ODbL) 1.0</a>.</p><p>The app shows source attribution and status in context. Production distribution remains subject to confirmation of the provider’s current API terms, rate limits, attribution requirements, and permission for the intended use. No other production provider is promised by this page.</p></section>
    <section aria-labelledby="en-demo"><h2 id="en-demo">3. Recorded Demo airspace</h2><p>Recorded Demo is a small bundled deterministic synthetic scene used for previews and offline demonstrations. It is marked <strong>DEMO · RECORDED AIRSPACE · SYNTHETIC</strong>, loops within a bounded duration, and is not current aircraft data or a geographic observation.</p></section>
    <section aria-labelledby="en-third"><h2 id="en-third">4. Third-party software and services</h2><p>AeroWisp uses Apple platform frameworks, including SwiftUI, Core Location, StoreKit, ImageIO, and related system services. Apple trademarks and services remain Apple’s property. The app may contact a selected data provider or the iOS sharing destination you choose; those parties’ terms and privacy policies apply to those interactions.</p><p>This page is an attribution and notice page. It is not a license to copy or redistribute the AeroWisp application, interface, brand, or original content.</p></section>
  </div><div data-lang="zh">
    <div className="callout warning-callout"><p><strong>署名不等于可用性承诺。</strong>数据提供方的覆盖、条款、接口和商业许可可能变化。在发布或商业使用前，请查看提供方当前的官方条款。</p></div>
    <section aria-labelledby="zh-app"><h2 id="zh-app">一、AeroWisp 原创内容</h2><p>AeroWisp 的原创代码、界面、视觉系统、内置配置、录制场景编排、文档和品牌均为 © 2026 guogxy，保留所有权利，除非另有第三方声明。雷达视觉语言是原创的电影感表达，不复制任何电影、游戏或其他娱乐作品的知识产权。</p></section>
    <section aria-labelledby="zh-live"><h2 id="zh-live">二、实时空域数据</h2><p>当 App 配置了该数据源时，实时飞机数据可能由 <a href="https://adsb.lol/" target="_blank" rel="noopener noreferrer">adsb.lol</a> 提供。adsb.lol 的信息依据 <a href="https://opendatacommons.org/licenses/odbl/1-0/" target="_blank" rel="noopener noreferrer">Open Database License（ODbL）1.0</a> 提供。</p><p>App 会在相应位置显示数据源署名和状态。正式发布仍需确认提供方当前的 API 条款、速率限制、署名要求和预期用途的许可。本页面不承诺其他生产数据提供方。</p></section>
    <section aria-labelledby="zh-demo"><h2 id="zh-demo">三、Recorded Demo 空域</h2><p>Recorded Demo 是内置的小型确定性合成场景，用于预览和离线演示。它会标记为<strong> DEMO · RECORDED AIRSPACE · SYNTHETIC</strong>，在有限时长内循环，不是当前飞机数据或地理观测。</p></section>
    <section aria-labelledby="zh-third"><h2 id="zh-third">四、第三方软件与服务</h2><p>AeroWisp 使用 Apple 平台框架，包括 SwiftUI、Core Location、StoreKit、ImageIO 及相关系统服务。Apple 的商标和服务属于 Apple。App 可能联系你选择的数据提供方或 iOS 分享目的地；这些交互适用相应方的条款和隐私政策。</p><p>本页面用于署名和声明，并不授予复制或重新分发 AeroWisp App、界面、品牌或原创内容的许可。</p></section>
  </div></InfoPage>; }
