import type { Metadata } from "next";
import Link from "next/link";
import { InfoPage } from "../legal-page";

export const metadata: Metadata = { title: "Privacy policy", description: "AeroWisp privacy policy." };
const toc = [{ id: "en-collect", label: "Information we use" }, { id: "en-location", label: "Location" }, { id: "en-data", label: "Airspace data" }, { id: "en-storage", label: "On-device storage" }, { id: "en-share", label: "Sharing" }, { id: "en-contact", label: "Contact" }];
const tocZh = [{ id: "zh-collect", label: "我们使用的信息" }, { id: "zh-location", label: "位置" }, { id: "zh-data", label: "空域数据" }, { id: "zh-storage", label: "设备内存储" }, { id: "zh-share", label: "分享" }, { id: "zh-contact", label: "联系" }];

export default function PrivacyPage() { return <InfoPage eyebrow="AeroWisp privacy" eyebrowZh="AeroWisp 隐私政策" title="Quiet by design." titleZh="安静地保护隐私。" intro="AeroWisp is designed around observation, not advertising profiles. This policy explains what the app uses, where it stays, and what it does not do." introZh="AeroWisp 围绕观察而设计，而不是广告画像。本政策说明 App 使用哪些信息、它们保存在哪里，以及它不会做什么。" meta="Last updated August 16, 2026" metaZh="最后更新：2026 年 8 月 16 日" toc={toc} tocZh={tocZh}><div data-lang="en">
    <div className="callout warning-callout"><p><strong>In brief.</strong> AeroWisp has no advertising trackers and does not sell personal information. Location is requested only when you choose a location-based feature. The app is not a navigation, air-traffic-control, or safety-decision service.</p></div>
    <section aria-labelledby="en-collect"><h2 id="en-collect">1. Information we use</h2><p>AeroWisp may use the information needed to provide the feature you select: a chosen map center, a saved airspace name or airport code, display preferences, locally observed aircraft history, and StoreKit purchase state supplied by Apple. The app does not ask for an account to use the local radar.</p><p>We do not use advertising identifiers, cross-app tracking, or a behavioral advertising profile. We do not intentionally collect precise location in a remote account database.</p></section>
    <section aria-labelledby="en-location"><h2 id="en-location">2. Location access</h2><p>Location access is optional. If you choose <em>Follow Me</em> or another location-centered feature, iOS provides a location to the app so it can center the local radar. You can deny or later revoke permission in iOS Settings; search and manually chosen airspaces remain available.</p><p>AeroWisp does not use location for advertising, background tracking, or navigation. The current or selected radar center may be stored on the device as the last-used center, and saved airspaces remain local unless you choose to share them. If Live is selected, the center and radius needed for the request are sent to the configured provider. The provider and normal network infrastructure may also see technical request metadata such as IP address, time, and URL information according to their own policies. AeroWisp does not create a remote location account or advertising profile.</p></section>
    <section aria-labelledby="en-data"><h2 id="en-data">3. Airspace and network data</h2><p>When Live is selected, AeroWisp requests nearby aircraft data from the configured provider and displays provider attribution and status in the app. Availability, coverage, retention, and terms depend on that provider. A network provider may receive the center and radius needed to answer the request.</p><p>Recorded Demo is bundled deterministic synthetic data. It is not a claim about current aircraft or current airspace. AeroWisp does not silently replace a failed Live feed with simulated aircraft.</p></section>
    <section aria-labelledby="en-storage"><h2 id="en-storage">4. On-device storage and retention</h2><p>Saved airspaces, settings, themes, locally observed history, and exported Airspace Portrait files are stored on the device unless you choose an iOS sharing destination. Local stores are deliberately bounded: portrait temporary files are maintained with a seven-day, twelve-file, 48 MiB policy; the URL cache has bounded memory and disk limits; Diary history has retention and size caps.</p><p>Removing the app or clearing its data may remove local content. iOS may back up app data according to your device settings; AeroWisp does not operate a separate cloud account for this content.</p></section>
    <section aria-labelledby="en-share"><h2 id="en-share">5. Sharing and purchases</h2><p>When you use the iOS share sheet, the selected image or Radar Code is sent to the destination you choose. Review that destination’s privacy practices. Purchases and restore/refund records are handled by Apple’s StoreKit and App Store systems; AeroWisp receives only the entitlement result needed to unlock the feature.</p></section>
    <section aria-labelledby="en-contact" className="contact-panel"><h2 id="en-contact">6. Questions</h2><p>For privacy questions or a correction request, use the support address on the Support page. Do not send passwords, payment details, or private coordinates in a support email.</p><Link className="button button-primary" href="/support/">Open support</Link></section><p className="small-print">When you visit this website, GitHub Pages may process basic request logs and technical metadata under GitHub’s privacy policy. This site does not add independent advertising analytics.</p>
  </div><div data-lang="zh">
    <div className="callout warning-callout"><p><strong>简要说明。</strong>AeroWisp 不含广告跟踪器，也不出售个人信息。只有在你选择基于位置的功能时，App 才会请求位置权限。本 App 不是导航、空中交通管制或安全决策服务。</p></div>
    <section aria-labelledby="zh-collect"><h2 id="zh-collect">一、我们使用的信息</h2><p>AeroWisp 只使用完成你所选功能所需的信息：地图中心、保存的空域名称或机场代码、显示偏好、本地观察到的飞机历史，以及 Apple StoreKit 提供的购买状态。使用本地雷达不需要注册账户。</p><p>我们不使用广告标识符、跨 App 跟踪或行为广告画像，也不会有意把精确位置收集到远程账户数据库中。</p></section>
    <section aria-labelledby="zh-location"><h2 id="zh-location">二、位置权限</h2><p>位置权限是可选的。当你选择“Follow Me”或其他以位置为中心的功能时，iOS 会向 App 提供位置，用于居中本地雷达。你可以拒绝或在“设置”中撤销权限；搜索和手动选择空域仍可使用。</p><p>AeroWisp 不把位置用于广告、后台跟踪或导航。当前或选定的雷达中心可能作为上次使用的中心保存在设备本地；保存的空域也会留在本地，除非你主动分享。选择 Live 时，请求所需的中心与半径会发送给配置的数据提供方；提供方和正常网络基础设施也可能依据各自政策看到 IP、时间、URL 等技术请求元数据。AeroWisp 不建立远程位置账户或广告画像。</p></section>
    <section aria-labelledby="zh-data"><h2 id="zh-data">三、空域与网络数据</h2><p>选择 Live 时，AeroWisp 会向配置的数据提供方请求附近飞机数据，并在 App 中显示数据源署名和状态。可用性、覆盖、保留方式和条款取决于数据提供方；网络提供方可能会收到回答请求所需的中心与半径。</p><p>Recorded Demo 是内置的确定性合成数据，不代表当前飞机或当前空域。实时数据失败时，AeroWisp 不会悄悄用模拟飞机替代。</p></section>
    <section aria-labelledby="zh-storage"><h2 id="zh-storage">四、设备内存储与保留期限</h2><p>保存的空域、设置、主题、本地观察历史和导出的空域肖像保存在设备上，除非你主动选择 iOS 分享目的地。设备内存储有明确上限：临时肖像文件按 7 天、12 个文件、48 MiB 维护；URL 缓存有内存和磁盘上限；Diary 历史有保留期限和大小上限。</p><p>删除 App 或清除数据可能会删除本地内容。iOS 可能依照你的设备设置备份 App 数据；AeroWisp 不运营独立的云账户来保存这些内容。</p></section>
    <section aria-labelledby="zh-share"><h2 id="zh-share">五、分享与购买</h2><p>使用 iOS 分享面板时，所选图片或 Radar Code 会发送给你选择的目的地，请查看该目的地的隐私政策。购买、恢复和退款记录由 Apple 的 StoreKit 与 App Store 系统处理；AeroWisp 只接收解锁功能所需的权益结果。</p></section>
    <section aria-labelledby="zh-contact" className="contact-panel"><h2 id="zh-contact">六、问题</h2><p>如有隐私问题或更正请求，请使用“支持”页面上的邮箱。请不要在邮件中发送密码、支付信息或私人坐标。</p><Link className="button button-primary" href="/support/">打开支持页面</Link></section><p className="small-print">访问本官网时，GitHub Pages 可能依据 GitHub 的隐私政策处理基本请求日志和技术元数据；本网站未配置独立的广告分析脚本。</p>
  </div></InfoPage>; }
