import Link from "next/link";
import { SiteFooter, SiteHeader } from "./site-chrome";

const features = [
  { n: "01", title: "A living radar", titleZh: "一张持续呼吸的雷达", en: "Track nearby airspace with a calm Canvas instrument, interpolated movement, range rings, labels, and honest source status.", zh: "用平静的 Canvas 仪表查看附近空域：连续运动、距离圈、目标标签，以及清楚的数据源状态。" },
  { n: "02", title: "World Tour", titleZh: "世界巡航", en: "Move between airport-focused airspaces with dwell, quiet hours, pause, and smooth cinematic transitions.", zh: "在机场重点空域之间巡航，支持停留、安静时段、暂停和连续的电影感转场。" },
  { n: "03", title: "Radar Studio", titleZh: "雷达工作室", en: "Shape colors, sweeps, labels, panels, layouts, and cinematic instruments into a radar that feels like yours.", zh: "调整色彩、扫描线、标签、面板、布局和电影感仪表，做出属于你的雷达。" },
  { n: "04", title: "Time Lens", titleZh: "时间镜头", en: "Replay a bounded local window with Ghost Trails, keeping observed history separate from live airspace.", zh: "用 Ghost Trails 回看有限的本地时间窗口，让已观察历史与实时空域清楚分开。" },
  { n: "05", title: "Airspace Portrait", titleZh: "空域肖像", en: "Compose a still portrait of the current sky, preview it, and export the same rendered image for sharing.", zh: "把当前天空定格成一幅肖像，预览与导出使用同一张真实渲染图。" },
  { n: "06", title: "Made for staying", titleZh: "为长时间观看而生", en: "Display Mode, Saved Airspaces, Follow Me, bounded storage, and graceful Live / Recorded Demo states keep the experience reliable.", zh: "Display Mode、保存空域、Follow Me、有边界的存储，以及清晰的 Live / Recorded Demo 状态，让长时间观看更可靠。" },
];

function RadarIllustration() {
  return <div className="radar-device" role="img" aria-label="AeroWisp radar illustration"><div className="radar-topline"><span><i className="live-dot" /> LIVE AIRSPACE</span><b>12.6 NM</b></div><div className="radar-screen"><span className="radar-cross horizontal" /><span className="radar-cross vertical" /><span className="radar-ring ring-one" /><span className="radar-ring ring-two" /><span className="radar-ring ring-three" /><span className="radar-sweep" /><span className="radar-target target-a" /><span className="radar-target target-b" /><span className="radar-target target-c" /><span className="radar-target target-d" /><span className="north-mark">N</span><span className="radar-center" /></div><div className="radar-readout"><span>HEADING <b>000°</b></span><span>TRACKS <b>07</b></span><span>AGE <b>12s</b></span></div></div>;
}

export default function Home() {
  return <><SiteHeader /><main id="main-content">
    <section className="hero wrap"><div className="hero-copy"><p className="eyebrow"><span data-lang="en">An instrument for the living sky</span><span data-lang="zh">为正在发生的天空而生</span></p><div data-lang="en"><h1>See the sky<span>as it moves.</span></h1><p className="lede">A cinematic live-airspace instrument and ambient display for iPhone and iPad. Watch aircraft move through the real sky—or enter a recorded scene when you want a quiet, dependable demo.</p></div><div data-lang="zh"><h1>看见天空<span>如何流动。</span></h1><p className="lede">一款电影感的实时空域仪表与环境显示 App，适用于 iPhone 和 iPad。观看飞机穿过真实天空，也可以在需要安静、稳定体验时进入录制演示。</p></div><div className="hero-actions"><Link className="button button-primary" href="#features"><span data-lang="en">Explore AeroWisp</span><span data-lang="zh">探索 AeroWisp</span><span aria-hidden="true"> ↓</span></Link><Link className="button button-secondary" href="/privacy/"><span data-lang="en">Privacy by design</span><span data-lang="zh">隐私设计</span></Link></div><p className="availability"><span className="pulse-line" /> <span data-lang="en">Live when you choose it · synthetic demo when you choose it</span><span data-lang="zh">你选择实时，或选择明确标记的合成演示</span></p></div><RadarIllustration /></section>
    <section className="statement-section"><div className="wrap statement-grid"><p className="eyebrow"><span data-lang="en">Not a control tower</span><span data-lang="zh">不是控制塔</span></p><h2><span data-lang="en">A quieter way to notice the airspace around you.</span><span data-lang="zh">以更安静的方式，注意你身边的空域。</span></h2><p><span data-lang="en">AeroWisp is for curiosity, atmosphere, and observation. It is not a navigation, air-traffic-control, or safety-decision tool.</span><span data-lang="zh">AeroWisp 用于好奇、氛围与观察。它不是导航、空中交通管制或安全决策工具。</span></p></div></section>
    <section className="feature-section" id="features"><div className="wrap"><div className="section-heading"><div><p className="eyebrow"><span data-lang="en">One sky, many ways to see it</span><span data-lang="zh">同一片天空，多种观看方式</span></p><h2><span data-lang="en">Built for the long look.</span><span data-lang="zh">适合慢慢看。</span></h2></div><p><span data-lang="en">From a quick glance at nearby flights to a two-hour ambient display, AeroWisp keeps the signal legible and the spectacle restrained.</span><span data-lang="zh">从快速查看附近航班，到长时间的环境显示，AeroWisp 让信息清晰，让氛围克制。</span></p></div><div className="feature-grid">{features.map((feature) => <article key={feature.n} className="feature-card"><span className="feature-number">{feature.n}</span><h3><span data-lang="en">{feature.title}</span><span data-lang="zh">{feature.titleZh}</span></h3><p><span data-lang="en">{feature.en}</span><span data-lang="zh">{feature.zh}</span></p></article>)}</div></div></section>
    <section className="showcase-section wrap"><div className="showcase-copy"><p className="eyebrow"><span data-lang="en">A source you can read</span><span data-lang="zh">看得懂的数据来源</span></p><h2><span data-lang="en">Live is live. Demo is demo.</span><span data-lang="zh">实时就是实时，演示就是演示。</span></h2><p data-lang="en">When Live is selected, failed live data does not quietly turn into simulated aircraft. Recorded Demo is a bounded, deterministic scene and says so on screen.</p><p data-lang="zh">选择 Live 时，实时数据失败不会悄悄变成模拟飞机。Recorded Demo 是有边界、可重复的录制场景，并会在界面中明确说明。</p><Link className="inline-link" href="/licenses/"><span data-lang="en">Read data &amp; license notes</span><span data-lang="zh">查看数据与许可说明</span><span aria-hidden="true"> →</span></Link></div><div className="source-card"><div><span className="source-kicker">CURRENT SOURCE</span><strong>DEMO · RECORDED AIRSPACE</strong><small>SYNTHETIC · 120s LOOP</small></div><div className="source-bars" aria-hidden="true"><i /><i /><i /><i /><i /><i /><i /><i /></div></div></section>
    <section className="trust-section wrap"><div><p className="eyebrow"><span data-lang="en">Private by design</span><span data-lang="zh">从设计上保护隐私</span></p><h2><span data-lang="en">Observation without ad profiles.</span><span data-lang="zh">观察天空，不建立广告画像。</span></h2></div><div><p data-lang="en">Location is requested only for features you choose, such as centering the radar or Follow Me. If Live is selected, the chosen center and radius are sent to the configured provider so it can answer the request. AeroWisp has no advertising trackers, and saved airspaces and local history are bounded on-device.</p><p data-lang="zh">位置仅在你选择相关功能时使用，例如将雷达居中或 Follow Me。选择 Live 时，选定的中心与半径会发送给配置的数据提供方，以便返回请求结果。AeroWisp 不含广告跟踪器，保存的空域和本地历史均有边界地保存在设备上。</p><Link className="inline-link" href="/privacy/"><span data-lang="en">Read the privacy policy</span><span data-lang="zh">阅读隐私政策</span><span aria-hidden="true"> →</span></Link></div></section>
    <section className="legal-cards wrap" aria-label="AeroWisp information"><Link href="/support/"><span>01</span><strong data-lang="en">Support</strong><strong data-lang="zh">技术支持</strong><i aria-hidden="true">↗</i></Link><Link href="/privacy/"><span>02</span><strong data-lang="en">Privacy</strong><strong data-lang="zh">隐私政策</strong><i aria-hidden="true">↗</i></Link><Link href="/terms/"><span>03</span><strong data-lang="en">Terms of use</strong><strong data-lang="zh">使用条款</strong><i aria-hidden="true">↗</i></Link></section>
  </main><SiteFooter /></>;
}
