import type { Metadata } from "next";
import Link from "next/link";
import { InfoPage } from "../legal-page";

export const metadata: Metadata = { title: "Terms of use", description: "AeroWisp terms of use." };
const toc = [{ id: "en-accept", label: "Acceptance" }, { id: "en-purpose", label: "Purpose and limits" }, { id: "en-data", label: "Data and availability" }, { id: "en-purchase", label: "Purchases" }, { id: "en-content", label: "Your content" }, { id: "en-liability", label: "Disclaimers" }];
const tocZh = [{ id: "zh-accept", label: "接受条款" }, { id: "zh-purpose", label: "用途与限制" }, { id: "zh-data", label: "数据与可用性" }, { id: "zh-purchase", label: "购买" }, { id: "zh-content", label: "你的内容" }, { id: "zh-liability", label: "免责声明" }];

export default function TermsPage() { return <InfoPage eyebrow="AeroWisp terms" eyebrowZh="AeroWisp 使用条款" title="Keep the signal honest." titleZh="让信号保持诚实。" intro="These terms set the boundaries for using AeroWisp, its visual systems, local tools, and data connections." introZh="这些条款说明使用 AeroWisp、视觉系统、本地工具和数据连接时的边界。" meta="Last updated August 16, 2026" metaZh="最后更新：2026 年 8 月 16 日" toc={toc} tocZh={tocZh}><div data-lang="en">
    <div className="callout warning-callout"><p><strong>Important use restriction.</strong> AeroWisp is for curiosity, ambient display, and personal observation. Do not use it for navigation, air-traffic control, dispatch, emergency response, flight separation, or any safety-critical decision.</p></div>
    <section aria-labelledby="en-accept"><h2 id="en-accept">1. Acceptance</h2><p>By installing or using AeroWisp, you agree to these terms. If you do not agree, do not use the app. You must follow applicable laws, Apple’s terms, and the terms of any data provider you access through the app.</p></section>
    <section aria-labelledby="en-purpose"><h2 id="en-purpose">2. Purpose and limits</h2><p>AeroWisp is a visual instrument for viewing nearby or selected airspace. Positions, names, headings, altitude, speed, route details, interpolated movement, and labels may be delayed, incomplete, inaccurate, or unavailable. Display Mode and Recorded Demo are designed for observation and atmosphere, not operational decisions.</p><p>Do not infer that an aircraft is safe, unsafe, authorized, nearby, or on a particular route from the app. Follow official aviation sources and local authorities for any real-world safety or travel decision.</p></section>
    <section aria-labelledby="en-data"><h2 id="en-data">3. Data and availability</h2><p>Live data depends on network access, provider coverage, provider terms, and service availability. AeroWisp may show stale, empty, or provider-labeled states. Recorded Demo is synthetic and bounded. We do not promise uninterrupted availability, a particular coverage area, or a specific update interval.</p></section>
    <section aria-labelledby="en-purchase"><h2 id="en-purchase">4. Purchases</h2><p>Radar Studio access, if offered, is a one-time in-app purchase handled by Apple. Prices, taxes, payment authorization, refunds, and cancellation are controlled by Apple and the storefront in which you purchase. A verified Apple entitlement is required for paid features.</p></section>
    <section aria-labelledby="en-content"><h2 id="en-content">5. Your content and sharing</h2><p>You keep ownership of the locations, notes, themes, Radar Codes, and images you create. You are responsible for the content you share and for ensuring that any shared material does not expose information you intend to keep private. The app’s original code, design, brand, and bundled content remain protected by applicable intellectual-property law.</p></section>
    <section aria-labelledby="en-liability"><h2 id="en-liability">6. Disclaimers</h2><p>To the extent permitted by law, AeroWisp is provided on an “as available” basis without a guarantee that every feature, provider, location, or export will be available or error-free. We are not responsible for decisions made from the app’s information. Nothing here limits rights that cannot legally be limited.</p><p>We may update the app or these terms. The current version will be posted on this page. Continued use after an update means you accept the updated terms.</p></section>
    <section className="contact-panel"><p className="eyebrow">Questions</p><h2>Need clarification?</h2><p>Read the <Link href="/support/">support page</Link> for practical help or contact the address listed there.</p></section>
  </div><div data-lang="zh">
    <div className="callout warning-callout"><p><strong>重要使用限制。</strong>AeroWisp 用于好奇、环境显示和个人观察。不得用于导航、空中交通管制、调度、应急响应、飞行间隔或任何安全关键决策。</p></div>
    <section aria-labelledby="zh-accept"><h2 id="zh-accept">一、接受条款</h2><p>安装或使用 AeroWisp 即表示你同意本条款。如不同意，请不要使用 App。你还必须遵守适用法律、Apple 条款和通过 App 访问的数据提供方条款。</p></section>
    <section aria-labelledby="zh-purpose"><h2 id="zh-purpose">二、用途与限制</h2><p>AeroWisp 是用于查看附近或指定空域的视觉仪表。位置、名称、航向、高度、速度、航线详情、插值移动和标签可能延迟、不完整、不准确或不可用。Display Mode 与 Recorded Demo 用于观察和氛围，不用于运行决策。</p><p>不得根据 App 推断飞机是否安全、危险、获准飞行、在附近或正在某条航线上。任何现实中的安全或出行决策，都应参考官方航空来源和当地主管部门。</p></section>
    <section aria-labelledby="zh-data"><h2 id="zh-data">三、数据与可用性</h2><p>实时数据取决于网络、提供方覆盖、提供方条款和服务可用性。AeroWisp 可能显示过期、空数据或带数据源说明的状态。Recorded Demo 是有边界的合成数据。我们不承诺持续可用、特定覆盖范围或固定更新间隔。</p></section>
    <section aria-labelledby="zh-purchase"><h2 id="zh-purchase">四、购买</h2><p>如提供 Radar Studio 权益，该功能通过 Apple 处理的一次性 App 内购买获得。价格、税费、支付授权、退款和取消由 Apple 及购买所在商店控制。付费功能需要经验证的 Apple 权益。</p></section>
    <section aria-labelledby="zh-content"><h2 id="zh-content">五、你的内容与分享</h2><p>你保留自己创建的地点、备注、主题、Radar Code 和图片的所有权。你需要对分享的内容负责，确保不会泄露想要保留私密的信息。App 的原创代码、设计、品牌和内置内容受适用知识产权法律保护。</p></section>
    <section aria-labelledby="zh-liability"><h2 id="zh-liability">六、免责声明</h2><p>在法律允许的范围内，AeroWisp 按“现状”和“可用”提供，不保证每个功能、数据提供方、地点或导出始终可用或没有错误。我们不对根据 App 信息作出的决定负责。本条款不限制法律上不能限制的权利。</p><p>我们可能更新 App 或本条款，当前版本会发布在本页面。更新后继续使用即表示接受更新后的条款。</p></section>
    <section className="contact-panel"><p className="eyebrow">问题</p><h2>需要说明？</h2><p>请阅读<Link href="/support/">支持页面</Link>获取实用帮助，或联系页面列出的邮箱。</p></section>
  </div></InfoPage>; }
