import type { Metadata } from "next";
import { InfoPage } from "../legal-page";

const supportAddress = "gggxxxyyyy@gmail.com";

export const metadata: Metadata = { title: "Support", description: "Help and contact information for AeroWisp." };
const toc = [{ id: "en-start", label: "Start here" }, { id: "en-live", label: "Live and Demo" }, { id: "en-location", label: "Location" }, { id: "en-portrait", label: "Portrait export" }, { id: "en-purchase", label: "Purchases" }, { id: "en-contact", label: "Contact" }];
const tocZh = [{ id: "zh-start", label: "先尝试这些步骤" }, { id: "zh-live", label: "Live 与 Demo" }, { id: "zh-location", label: "位置" }, { id: "zh-portrait", label: "肖像导出" }, { id: "zh-purchase", label: "购买" }, { id: "zh-contact", label: "联系我们" }];

export default function SupportPage() { return <InfoPage eyebrow="AeroWisp support" eyebrowZh="AeroWisp 技术支持" title="Stay in the signal." titleZh="让信号保持清晰。" intro="A few practical checks for the radar, location, Display Mode, portrait export, and Radar Studio." introZh="这里提供雷达、位置、Display Mode、肖像导出和 Radar Studio 的实用排查方法。" toc={toc} tocZh={tocZh}><div data-lang="en">
    <section aria-labelledby="en-start"><h2 id="en-start">1. Start here</h2><ol><li>Update AeroWisp and iOS or iPadOS to the latest available versions.</li><li>Confirm the expected network and permission state, then close and reopen the app.</li><li>Note the app version, device model, system version, selected feed, and the shortest steps that reproduce the issue.</li><li>If a screenshot helps, hide private coordinates or personal notes first.</li></ol></section>
    <section aria-labelledby="en-live"><h2 id="en-live">2. Live or Demo is empty</h2><p>Live airspace depends on provider coverage, network reachability, selected center and radius, and provider response. Check the source label and age shown in the radar. An empty or stale Live state is honest provider status; it is not silently replaced by synthetic aircraft.</p><p>Choose Recorded Demo when you want the bundled deterministic scene. It is labeled <strong>DEMO · RECORDED AIRSPACE · SYNTHETIC</strong> and does not represent current aircraft.</p></section>
    <section aria-labelledby="en-location"><h2 id="en-location">3. Location or Follow Me</h2><p>Location is optional. Open iOS Settings → Privacy &amp; Security → Location Services to review access. Search and manually selected airspaces work without location. Follow Me uses the current location only to center the radar and can be turned off at any time. If Live is selected, the chosen center and radius are sent to the configured provider for the aircraft request.</p></section>
    <section aria-labelledby="en-portrait"><h2 id="en-portrait">4. Portrait preview or export</h2><p>Portrait preview is built from the same rendered PNG used by Share. Wait for the export to finish before leaving the screen. If it is blank, retry once after returning to the current airspace, and include the device model, orientation, theme, and whether the feed was Live or Demo in a support message.</p></section>
    <section aria-labelledby="en-purchase"><h2 id="en-purchase">5. Radar Studio purchase or restore</h2><p>Open Settings → Radar Studio and use Restore Purchases with the Apple ID that made the purchase. Apple manages payment, cancellation, and refunds. Never send an Apple ID password or payment information in a support email.</p></section>
    <section aria-labelledby="en-contact" className="contact-panel"><p className="eyebrow">Contact</p><h2 id="en-contact">Still need help?</h2><p>Describe what you expected, what happened, and the shortest reproduction steps. Include the app version, device model, and iOS or iPadOS version when relevant.</p><a className="button button-primary" href={`mailto:${supportAddress}?subject=AeroWisp%20Support`}>Email {supportAddress}</a><p className="small-print">Please do not include passwords, payment details, or exact private coordinates.</p></section>
  </div><div data-lang="zh">
    <section aria-labelledby="zh-start"><h2 id="zh-start">一、先尝试这些步骤</h2><ol><li>将 AeroWisp 和 iOS 或 iPadOS 更新到当前可用版本。</li><li>确认网络和权限状态符合预期，然后关闭并重新打开 App。</li><li>记录 App 版本、设备型号、系统版本、选择的源，以及能复现问题的最短步骤。</li><li>如需截图，请先隐藏私人坐标或个人备注。</li></ol></section>
    <section aria-labelledby="zh-live"><h2 id="zh-live">二、Live 或 Demo 没有目标</h2><p>实时空域取决于数据源覆盖、网络、选定的中心和半径，以及提供方响应。请查看雷达中显示的数据源和数据年龄。Live 为空或过期是诚实的数据源状态，不会悄悄替换成合成飞机。</p><p>如果想体验内置的确定性场景，请选择 Recorded Demo。它会标记为<strong> DEMO · RECORDED AIRSPACE · SYNTHETIC</strong>，不代表当前飞机。</p></section>
    <section aria-labelledby="zh-location"><h2 id="zh-location">三、位置或 Follow Me</h2><p>位置权限是可选的。打开 iOS“设置”→“隐私与安全性”→“定位服务”检查权限。没有位置权限也可以搜索和手动选择空域。Follow Me 使用当前位置来居中雷达，可以随时关闭；如果选择 Live，请求所需的中心与半径会发送给配置的数据提供方。</p></section>
    <section aria-labelledby="zh-portrait"><h2 id="zh-portrait">四、肖像预览或导出</h2><p>肖像预览使用与分享相同的实际 PNG 渲染结果。请等待导出完成后再离开页面。如果出现空白，返回当前空域后重试一次，并在支持邮件中注明设备型号、方向、主题以及使用的是 Live 还是 Demo。</p></section>
    <section aria-labelledby="zh-purchase"><h2 id="zh-purchase">五、Radar Studio 购买或恢复</h2><p>打开“设置”→“Radar Studio”，使用购买时的 Apple ID 执行“恢复购买”。付款、取消和退款由 Apple 管理。请勿在支持邮件中发送 Apple ID 密码或付款信息。</p></section>
    <section aria-labelledby="zh-contact" className="contact-panel"><p className="eyebrow">联系我们</p><h2 id="zh-contact">仍需要帮助？</h2><p>请说明预期结果、实际现象和最短复现步骤；如相关，请提供 App 版本、设备型号和 iOS 或 iPadOS 版本。</p><a className="button button-primary" href={`mailto:${supportAddress}?subject=AeroWisp%20Support`}>发送邮件至 {supportAddress}</a><p className="small-print">请勿发送密码、付款信息或私人地点的精确坐标。</p></section>
  </div></InfoPage>; }
